### PR TITLE
Tests/fix espresso tests

### LINKED ISSUE #57: Fix Existing Espresso Tests that are failing
Within the AndroidTest directory, there are currently existing test which are failing due to unknown reasons. These must be fixed in order to run espresso tests for the application.

Ideal Hours: 2h
Related Story: #56

### PR DESCRIPTION
**Pull request by benrs**
Fixes needed to make espresso tests work + bypass registration. Note that if the apk reinstalls itself you'll have to re-run the espresso test for bypassing registration, accepting all the native permission dialogs is the task of the user. Afterwards it'll register and send a false code which does not get verified but it sets up the database properly. Note that this hasn't been intensively tested and may cause problems when running espresso tests as it is not actually set up with Signal's servers.

Closes #57 #58.

### CODE REVIEW

**Review by claudds — APPROVED** [review]
Looks good

**Review by jacobrs — APPROVED** [review]

**Comment by jacobrs** [comment]
Did you test it with the emulator? What was your config? Its failing when I try to run the instrument tests.

**Comment by benrs** [comment]
I did test it with the emulator, can you give me the steps that you followed for failure?

**Comment by jacobrs** [comment]
I can try, but I just followed the default setup.
- click Edit Configurations...
- create new instrumented tests
- leave the defaults 
- run the tests

The first failure is:
```
java.lang.AssertionError: Didn't try to generate thumbnail
at org.thoughtcrime.securesms.database.AttachmentDatabaseTest.testThumbnailGenerationTaskRunWhenThumbnailMissing(AttachmentDatabaseTest.java:62)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:77)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:55)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:69)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:103)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
```

**Comment by benrs** [comment]
The DatabaseAttachmentTest doesn't work in general, we weren't able to run it previously so it wasn't being flagged. Just try to run the folder under `espressoTests`, run `getFakeVerificationTest` first which is a manual + automatic process (you have to accept all the native permission dialogs), afterwards set Signal as the default sms app. At this point you should be able to run any UI test.

**Pull request merged**
